### ISSUE TITLE
Usability - Add new Member date field format is not Clear

### ISSUE THREAD

**Issue by sskarmoutsos** [eaglefox82/squadronadmin#5]
![image](https://user-images.githubusercontent.com/50933691/58294679-d2a23b00-7e0e-11e9-9ab9-c23f739e7660.png)

When the user requires to enter a value into the Date field, It does not restrict them into typing the date in any specific order. It is not in the standard date format of DD-MM-YYYY

**Comment by eaglefox82** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Defect - Date View](https://trello.com/c/FBbZah7g/28-defect-date-view)
